accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),

]

charity_donation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.LandingPage.as_view(), name='landing_page'),
    path('donation/', views.AddDonation.as_view(), name='add_donation'),
    path('donation/done/', views.DoneDonation.as_view(), name='done_donation'),
]

accounts/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator, EmailValidator


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, first_name, last_name, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        extra_fields.setdefault('is_staff', False)
        return self._create_user(email, password, first_name, last_name, **extra_fields)

    def create_superuser(self, email, password, first_name, last_name, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, first_name, last_name, **extra_fields)


class User(AbstractUser):
    class Meta(AbstractUser.Meta):
        ordering = ('first_name', )

    username = None
    # TODO fix for polish letters
    name_validator = RegexValidator(r'^[a-zA-Z]+$', 'Enter a valid name. This value may contain only letters.')
    first_name = models.CharField(
        _('first name'),
        max_length=30,
        help_text=_('Required. 30 characters or fewer. Letters only.'),
        validators=[name_validator],
    )
    last_name = models.CharField(
        _('last name'),
        max_length=150,
        help_text=_('Required. 150 characters or fewer. Letters only.'),
        validators=[name_validator],
    )
    email_validator = EmailValidator()
    email = models.EmailField(
        _('email address'),
        unique=True,
        help_text=_('Required. Standard email format.'),
        validators=[email_validator],
        error_messages={
            'unique': _("A user with that email already exists."),
        },
    )

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

main/models.py
from django.conf import settings
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=32)


class Institution(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    types = [
        ('FU', 'Fundacja'),
        ('OP', 'Organizacja porządkowa'),
        ('ZL', 'Zbiórka lokalna')
    ]
    type = models.CharField(max_length=2, choices=types, default=1)
    categories = models.ManyToManyField(Category)


class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=32)  # ulica + nr domu
    phone_number = models.CharField(max_length=12)
    city = models.CharField(max_length=32)
    zip_code = models.CharField(max_length=6)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    pick_up_comment = models.CharField(max_length=256, null=True, default=None)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, default=None)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from accounts.models import User


class MyUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name")

accounts/views.py
from accounts.forms import MyUserCreationForm
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView


class Register(CreateView):
    form_class = MyUserCreationForm
    success_url = reverse_lazy("login")
    template_name = 'registration/register.html'


class Login(LoginView):
    template_name = 'registration/login.html'

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View

from accounts.models import User
from main.models import Category, Institution, Donation


class LandingPage(View):
    def get(self, request):
        context = {
            'fundacje': Institution.objects.filter(type__exact='FU'),
            'organizacje': Institution.objects.filter(type__exact='OP'),
            'zbiorki': Institution.objects.filter(type__exact='ZL'),
        }
        return render(request, 'index.html', context)


class AddDonation(LoginRequiredMixin, View):
    def get(self, request):
        context = {'categories': Category.objects.all(),
                   'institutions': Institution.objects.all()}
        return render(request, 'form.html', context)

    def post(self, request):
        quantity = request.POST.get('bags')
        institution = ""
        if request.POST.get('organization'):
            institution = Institution.objects.get(pk=request.POST.get('organization'))
        address = request.POST.get('address')
        phone_number = request.POST.get('phone')
        city = request.POST.get('city')
        zip_code = request.POST.get('postcode')
        pick_up_date = request.POST.get('date')
        pick_up_time = request.POST.get('time')
        pick_up_comment = request.POST.get('more_info')
        user = request.user

        if quantity and institution and address and phone_number and city and zip_code and pick_up_date and pick_up_time and user:
            dono = Donation.objects.create(
                quantity=quantity,
                institution=institution,
                address=address,
                phone_number=phone_number,
                city=city,
                zip_code=zip_code,
                pick_up_date=pick_up_date,
                pick_up_time=pick_up_time,
                pick_up_comment=pick_up_comment,
                user=user
            )

            dono.categories.set(request.POST.getlist('categories'))  # m2m
            dono.save()
            return HttpResponse(reverse_lazy('done_donation'))

        return HttpResponse('bląd, conij i popraw', status=500)


class DoneDonation(View):
    def get(self, request):
        return render(request, 'form-confirmation.html')

templates/__base__.html
<!DOCTYPE html>
{% load static %}
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href='{% static "main/css/style.css"%}' />
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
  </head>
  <body>
    <header class="{{ header_class }}">
      <nav class="container container--70">
        <ul class="nav--actions">
            {% if not user.is_authenticated %}
          <li><a href="{% url 'login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
          <li><a href="{% url 'register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
            {% else %}
                <li class="logged-user">
            Witaj {{ user.first_name }}
            <ul class="dropdown">
              <li><a href="#">Profil</a></li>
              <li><a href="#">Ustawienia</a></li>
              <li><a href="{% url 'logout' %}">Wyloguj</a></li>
            </ul>
          </li>
            {% endif %}
        </ul>

        <ul>
          <li><a href="{% url 'landing_page' %}" class="btn btn--without-border active">Start</a></li>
          <li><a href="{% url 'landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="{% url 'landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="{% url 'landing_page' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="{% url 'add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

    {% block slogan %}
    {% endblock %}

    </header>

        {% block content %}
      {% endblock %}

    <footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
          <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>

          <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2019</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"><img src='{% static "main/images/icon-facebook.svg"%}'/></a>
          <a href="#" class="btn btn--small"><img src='{% static "main/images/icon-instagram.svg"%}'/></a>
        </div>
      </div>
    </footer>

    <script src='{% static "main/js/app.js" %}'></script>
  </body>
</html>

templates/form-confirmation.html
{% extends '__base__.html' %}
{% block slogan %}
    <div class="slogan container container--90">
        <div class="slogan--item">
          <h2>
            Dziękujemy za przesłanie formularza. Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
        </div>
    </div>
{% endblock %}

templates/form.html
{% extends '__base__.html' %}
{% block slogan %}
    <div class="slogan container container--90">
        <div class="slogan--item">

          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
    </div>
{% endblock %}
{% block content %}

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form method="post" action="{% url 'add_donation' %}">
            {% csrf_token %}
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="step1 active">
            <h3>Zaznacz co chcesz oddać:</h3>

            {% for category in categories %}
            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="{{ category.id }}"
                />
                <span class="checkbox"></span>
                <span class="description"
                  >{{ category.name }}</span
                >
              </label>
            </div>
              {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2" class="step2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" name="bags" step="1" min="1" />
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 3 -->
          <div data-step="3" class="step3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>
            {% for institution in institutions %}
            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio" name="organization" value="{{ institution.id }}" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">{{ institution.get_type_display }} "{{ institution.name }}"</div>
                  <div class="subtitle">Cel i misja: {{ institution.description }}</div>
                </span>
              </label>
                <input type="hidden" id="categories" value=
                        "{% for category in institution.categories.iterator %}{{ category.id }}, {% endfor %}"/>
            </div>

            {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 4 -->
          <div data-step="4" class="step4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" id="address" /> </label>
                </div>
                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" id="city" /> </label>
                </div>
                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" id="postcode" />
                  </label>
                </div>
                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone" id="phone" />
                  </label>
                </div>
              </div>
              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="date" id="date" /> </label>
                </div>
                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" id="time" /> </label>
                </div>
                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" id="more_info" rows="5"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text bags"></span>
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text institution"></span>
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="address form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                      <li></li>
                      <li></li>
                      <li></li>
                      <li></li>
                  </ul>
                </div>

                <div class="delivery form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                      <li></li>
                      <li></li>
                      <li></li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>

{% endblock %}

templates/index.html
{% extends '__base__.html' %}
{% load static %}

{% block slogan %}
    <div class="slogan container container--90">
        <div class="slogan--item">
            <h1>
                Zacznij pomagać!<br/>
                Oddaj niechciane rzeczy w zaufane ręce
            </h1>
        </div>
    </div>
{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <section id="stats" class="stats">
            <div class="container container--85">
                <div class="stats--item">
                    <em>10</em>
                    <h3>Oddanych worków</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum
                        tempora!</p>
                </div>

                <div class="stats--item">
                    <em>5</em>
                    <h3>Wspartych organizacji</h3>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil
                        cupiditate quas quam.</p>
                </div>

            </div>
        </section>
    {% endif %}

    <section id="steps" class="steps">
        <h2>Wystarczą 4 proste kroki</h2>

        <div class="steps--container">
            <div class="steps--item">
                <span class="icon icon--hands"></span>
                <h3>Wybierz rzeczy</h3>
                <p>ubrania, zabawki, sprzęt i inne</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--arrow"></span>
                <h3>Spakuj je</h3>
                <p>skorzystaj z worków na śmieci</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--glasses"></span>
                <h3>Zdecyduj komu chcesz pomóc</h3>
                <p>wybierz zaufane miejsce</p>
            </div>
            <div class="steps--item">
                <span class="icon icon--courier"></span>
                <h3>Zamów kuriera</h3>
                <p>kurier przyjedzie w dogodnym terminie</p>
            </div>
        </div>
        {% if not user.is_authenticated %}
            <a href="{% url 'register' %}" class="btn btn--large">Załóż konto</a>
        {% endif %}
    </section>

    <section id="about-us" class="about-us">
        <div class="about-us--text">
            <h2>O nas</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt
                libero optio esse quisquam illo omnis.</p>
            <img src='{% static "main/images/signature.svg" %}' class="about-us--text-signature" alt="Signature"/>
        </div>
        <div class="about-us--image"><img src='{% static "main/images/about-us.jpg" %}' alt="People in circle"/></div>
    </section>

    <section id="help" class="help">
        <h2>Komu pomagamy?</h2>

        <ul class="help--buttons">
            <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
            <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
            <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
        </ul>

        <!-- SLIDE 1 -->
        <div class="help--slides active" data-id="1">
            <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym
                się zajmują, komu pomagają i czego potrzebują.</p>

            <ul class="help--slides-items">
                {% for fundacja in fundacje %}
                    <li>
                        <div class="col">
                            <div class="title">Fundacja "{{ fundacja.name }}"</div>
                            <div class="subtitle">Cel i misja: {{ fundacja.description }}.</div>
                        </div>

                        <div class="col">
                            <div class="text">
                                {% for categorie in fundacja.categories.all %}{{ categorie.name }}, {% endfor %}</div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
            </ul>
            -->
        </div>


        <!-- SLIDE 2 -->
        <div class="help--slides" data-id="2">
            <p>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur
                accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
                quos suscipit corporis!
            </p>
            <ul class="help--slides-items">
                {% for org in organizacje %}
                    <li>
                        <div class="col">
                            <div class="title">Organizacja "{{ org.name }}"</div>
                            <div class="subtitle">Cel i misja: {{ org.description }}.</div>
                        </div>

                        <div class="col">
                            <div class="text">
                                {% for categorie in org.categories.all %}{{ categorie.name }}, {% endfor %}</div>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="3">3</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="4">4</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="5">5</a></li>
            </ul>
            -->
        </div>

        <!-- SLIDE 3 -->
        <div class="help--slides" data-id="3">
            <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci
                partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
            <ul class="help--slides-items">
                {% for zbiorka in zbiorki %}
                    <li>
                        <div class="col">
                            <div class="title">Zbiorka lokalna "{{ zbiorka.name }}"</div>
                            <div class="subtitle">Cel i misja: {{ zbiorka.description }}.</div>
                        </div>

                        <div class="col">
                            <div class="text">
                                {% for categorie in zbiorka.categories.all %}{{ categorie.name }}, {% endfor %}</div>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <!-- Pagination
            <ul class="help--slides-pagination">
              <li><a href="#" class="btn btn--small btn--without-border active" data-page="1">1</a></li>
              <li><a href="#" class="btn btn--small btn--without-border" data-page="2">2</a></li>
            </ul>
            -->
        </div>
    </section>
{% endblock %}

templates/login.html
{% extends '__base__.html' %}
{% block content %}
    <section class="login-page">
      <h2>Zaloguj się</h2>
      <form>
          {% csrf_token %}
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
          <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'register' %}" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zaloguj się</button> 
        </div>
      </form>
    </section>
{% endblock %}

templates/register.html
{% extends '__base__.html' %}
{% block content %}
    <section class="login-page">
      <h2>Załóż konto</h2>
      <form>
          {% csrf_token %}
        <div class="form-group">
          <input type="text" name="name" placeholder="Imię" />
        </div>
         <div class="form-group">
          <input type="text" name="surname" placeholder="Nazwisko" />
        </div>
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
        </div>
        <div class="form-group">
          <input type="password" name="password2" placeholder="Powtórz hasło" />
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'login' %}" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>
{% endblock %}